name: Build & Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-glx
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install django==4.1.2 djangorestframework==3.14.0 opencv-python-headless==4.6.0.66 pytest==7.1.3 torch==1.12.1 pydantic==1.10.2 loguru==0.6.0 tqdm==4.64.1 Pillow==9.2.0 diffusers==0.4.2 transformers==4.23.1 scikit-image==0.19.3

      - name: Clone repository
        run: git clone https://github.com/hben35/LamaCleaner.git

      - name: Move files
        run: |
          mv LamaCleaner/* .
          rm -rf LamaCleaner

      - name: Remove db.sqlite3
        run: rm -f db.sqlite3

      - name: Build Docker image
        run: docker build -t your-docker-username/lama-cleaner:latest .

      - name: Log in to Docker Hub
        run: docker login -u your-docker-username -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: docker push your-docker-username/lama-cleaner:latest

      - name: Deploy to CapRover
        uses: caprover/deploy-from-github@v1.0.1
        with:
          server: ${{ secrets.CAPROVER_SERVER }}
          app: ${{ secrets.APP_NAME }}
          token: ${{ secrets.APP_TOKEN }}
