name: Build & Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install django==4.1.2 djangorestframework==3.14.0 opencv-python-headless==4.6.0.66 pytest==7.1.3 torch==1.12.1 pydantic==1.10.2 loguru==0.6.0 tqdm==4.64.1 Pillow==9.2.0 diffusers==0.4.2 transformers==4.23.1 scikit-image==0.19.3

      - name: Clone LamaCleaner
        run: |
          git clone https://github.com/hben35/LamaCleaner.git LamaCleaner
          cp -r LamaCleaner/* .
          rm -rf LamaCleaner

      - name: Prepare deployment package
        run: |
          rm -rf venv
          tar -czvf deploy.tar .

      - name: Deploy App to CapRover
        uses: caprover/deploy-from-github@v1.0.1
        with:
          server: ${{ secrets.CAPROVER_SERVER }}
          app: ${{ secrets.APP_NAME }}
          token: ${{ secrets.APP_TOKEN }}
          tarFile: deploy.tar
